# Generated by Django 4.0.4 on 2022-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='elective',
            field=models.ManyToManyField(to='core.electivesubject'),
        ),
    ]
